### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by vincentvanhees** [emolinaro/PALMSpy#22]
I am continuing the thread started by @TeunRemmers in the HabitusGUI repo: https://github.com/habitus-eu/HabitusGUI/issues/69
The issue is not related to HabitusGUI and better discussed here in the PALMSpy repo.

Snapshot of the error, see other issue for full details:

```
23/02/08 13:52:58 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/02/08 13:53:59 ERROR Executor: Exception in task 2.0 in stage 320.0 (TID 1846)
java.lang.StackOverflowError
	at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2792)
	at java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3099)
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3109)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1837)
```

I first tried to reproduce the issue but kept running into more fundamental issues like json files not being correctly configured for his data. So, we then looked at it via Teun's account:

1. Teun is using the UCloud PALMSpy App 1.9.6. He did not have these problems when working on the exact same data in December 2022 with the old UCloud HABITUS app 1.9.6.
2. When we rename the files to be processed in the opposite order the above error occurs when processing a different file. So, the error is not file specific. 
3. Always a few files are processed correctly, indicating that it is not a problem with the file format.
4. Teun has been using the most powerful machine. I cannot remember whether he also tried with smaller machines. @TeunRemmers can you clarify?

**Comment by josefheidler** [comment]
@vincentvanhees  is this error still occurring? Can we reproduce this on local machine?

**Comment by vincentvanhees** [comment]
I have never been able to reproduce it because I kept running into various other errors, but the error is real based on the logs I saw from Teun's work. It seems it typically occurs when processing a range of files. 

It is unclear on what machines the problems occur. Teun tended to select the largest machine on UCloud, so maybe it is specific to that machine?

**Comment by emolinaro** [comment]
@vincentvanhees are you using all available cores and memory when processing the files? Which machine are you using? Please, play with the input parameters which set the number of cores and the maximum memory.

**Comment by TeunRemmers** [comment]
@emolinaro: 
@vincentvanhees and I are always using the x64 vCPU 384 GB RAM for testing.

**Comment by emolinaro** [comment]
@TeunRemmers using the largest machine is not enough. You still need to manually set the number of cores and the maximum executors memory. Note that PALMSpy v1.9.6 on UCloud is the same application which before was denoted as HABITUS v1.9.6. Thus, I exclude an issue of the current PALMSpy implementation, if the same dataset used to be processed correctly. The problem is most likely on a cluster node, but it is not possible to investigate it in detail with the information you provided.

**Comment by vincentvanhees** [comment]
> Please, play with the input parameters which set the number of cores and the maximum memory.

Thanks @emolinaro, this seems to clarify the problem. None of us has ever done this as we assumed that PALMSpy would figure out how to optimally use the machine it is run on. I do not think we can expect end-users to work this out: It is time consuming for them to check and update these settings with every run, it introduces the risk for mistakes when re-using the same json on a new machine, and it may be a waste of computing resources if users poorly select their settings.

So, I think what we need is:
- Addition of some level of automation of PALMSpy to adjust the parameters to the machine it is run on. Maybe cores and memory is enough.
- Review whether PALMSpy unnecessarily keeps data in memory when processing multiple files. For example, ideally no information should be kept on file 1 when starting to process file 2, all this could be stored to a temp file.
- PALMSpy to recognise when resources are not sufficient and cancel the analyses with a clear warning message before running into the stackoverflow error.
- If, after this there is still input from the user needed then ~~we~~ the end-user needs clear guidance on how to set these parameters.

**Comment by emolinaro** [comment]
@vincentvanhees, each data file is processed serially and the program clears the cache before starting the analysis of the next data file. Thus, point 2 above should not be relevant.

Note that, if the program crashes while processing a specific file, the user should NEVER restart the analysis on ALL data. 
It doesn't make any sense to consume resources rerunning a successful analysis. In fact, all the files which were successfully processed are saved in the PALMSpy output folder and are available on UCloud after the job ends.
The user should complete the analysis only on the remaining files, including the one which caused the crashed in the previous run. The user can merge all completed results at the end by writing a simple script, in whatever programming language. You can also do the merging in Excel.

**Comment by TeunRemmers** [comment]
> @TeunRemmers using the largest machine is not enough. You still need to manually set the number of cores and the maximum executors memory. Note that PALMSpy v1.9.6 on UCloud is the same application which before was denoted as HABITUS v1.9.6. Thus, I exclude an issue of the current PALMSpy implementation, if the same dataset used to be processed correctly. The problem is most likely on a cluster node, but it is not possible to investigate it in detail with the information you provided.

Thank you @emolinaro for your response. Just to be sure... how do I make the manual adjustments to the PALMSpy application?

**Comment by vincentvanhees** [comment]
@TeunRemmers these are the memory and cores parameters in the config file. However, I do not think you should be adjusting these as I explain above. @heidler is currently exploring how we can automate this or if not possible provide clear guidance.
