### ISSUE TITLE
Add installation instructions + integration test

### ISSUE THREAD

**Issue by vincentvanhees** [emolinaro/PALMSpy#7]
**Description of issue**

Installation is not clearly documented and scattered across: `setup.py`, `requirements.txt`, bash code in Dockerfile, `environment.yml`, and `habitus-1.9.4-py3-none-any.whl`. Additionally:

- It seems the requirement `Python < 3.8` should be clarified somewhere? For example, when setting up the conda environment?
- Library gmplot is used in a notebook but not declared in the requirements.txt file.
- The url for conda installation in the dockerfile is out of date.
- Setup.py does not clarify repo dependencies.
- Setup.py and requirements.txt do not clarify how to install PySpark

**Steps to resolve this:**

- [x] Fix issues with installation files, and remove any file that is no longer needed.
- [ ] Add integration test, e.g. with GitHub Actions. Linux may be sufficient for now, OSx and Windows nice for future.
- [ ] Create PyPi release, OR as an intermediate solution enable: `pip install git+https://github.com/emolinaro/PALMSpy.git`.
- [x] Add pip install instruction to README

Let me know if there is anything I can do to help.

**Comment by vincentvanhees** [comment]
hi @emolinaro I know you are still working on this, but if it is of any help I just tried out the current version and made the following observations:

**README:**
./dist/hab**is**tus-x.y.z-py3-none-any.whl should be /dist/hab**i**tus-x.y.z-py3-none-any.whl

I can make a PR but maybe it just as easy for you to make the edit.

After that the installation was successful. Next, I tried to test it out with the notebooks.

**Notebook data_proc_test.ipynb:**

_Cell 3:_ `ModuleNotFoundError: No module named 'line_profiler'`

If I comment out `%load_ext line_profiler` and continue...

_Cell 4:_ `JAVA_HOME is not set`...
Full message:
![image](https://user-images.githubusercontent.com/8362333/136389447-25731e26-8972-4e16-858b-e6d79eff6ee4.png)

For me, and possibly others, not familiar with using Java in Linux environment it may be good to have some guidance on how to get the Java version needed for PALMSpy. For example, should I follow: https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-20-04 ?

**Comment by emolinaro** [comment]
Hi @vincentvanhees,
are you running the code in an isolated Conda environment? If you install all the dependencies as shown in the `README` file, Java is automatically installed with Spark.

**Comment by vincentvanhees** [comment]
HI @emolinaro I am working from within the conda environment based on the steps in the README in a a clean installation of Ubuntu 20.

```
(palmspy) vincent@pythonVM:~/projects/PALMSpy$ java -version

Command 'java' not found, but can be installed with:

sudo apt install openjdk-11-jre-headless  # version 11.0.11+9-0ubuntu2~20.04, or
sudo apt install default-jre              # version 2:1.11-72
sudo apt install openjdk-13-jre-headless  # version 13.0.7+5-0ubuntu1~20.04
sudo apt install openjdk-16-jre-headless  # version 16.0.1+9-1~20.04
sudo apt install openjdk-17-jre-headless  # version 17+35-1~20.04
sudo apt install openjdk-8-jre-headless   # version 8u292-b10-0ubuntu1~20.04
```

```
(palmspy) vincent@pythonVM:~/projects/PALMSpy$ pyspark --version
JAVA_HOME is not set
```

When I scroll through the console messages produced by installation I do not see any error or warning signs.

According to [this](https://stackoverflow.com/questions/38747713/running-spark-on-linux-java-home-not-set-error) stackoverflow post the JAVA_HOME warning above is because JAVA_HOME needs to be specified inside `spark_env.sh`. However, I suspect that file was never created because JAVA has to be installed first before Spark can be configured.

**Comment by emolinaro** [comment]
This issue should be solved by installing `openjdk` within the Conda environment:
```
conda create -n palmspy python=3.7 openjdk=8.0 -y
```
You don't need to define `JAVA_HOME` in this way. 
This was tested with Ubuntu 20.04 and CentOS 8.

**Comment by vincentvanhees** [comment]
Thanks @emolinaro. After doing this the command line information indicates that the installation went well. However, when I then open the notebook (data_proc_test) it shows a Kernel error.

### Command line confirmation that installation went well:

```
(palmspy) vincent@pythonVM:~/projects/PALMSpy$ pip install ./dist/habitus-1.9.5-py3-none-any.whl 
Processing ./dist/habitus-1.9.5-py3-none-any.whl
Installing collected packages: habitus
Successfully installed habitus-1.9.5
(palmspy) vincent@pythonVM:~/projects/PALMSpy$ java -version
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)
(palmspy) vincent@pythonVM:~/projects/PALMSpy$ pyspark --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.2
      /_/
                        
Using Scala version 2.12.8, OpenJDK 64-Bit Server VM, 1.8.0_152-release
Branch 
Compiled by user  on 2019-04-18T23:18:13Z
Revision 
Url 
Type --help for more information.
```


### Kernel error:

![image](https://user-images.githubusercontent.com/8362333/136956666-db7e9f91-371e-4b2b-929e-92aaef963254.png)

and when I click on it I see:

```
Traceback (most recent call last):
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/vincent/anaconda3/envs/palmspy/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vincent/anaconda3/envs/palms/bin/python3': '/home/vincent/anaconda3/envs/palms/bin/python3'
```

In the last line it points at a non-existing directory with a **palms** folder, while my conda environment is called **palmspy**.
To exclude the unlikely possibility that I somehow have a palms environment that should not be there, I then did:
`conda clean --all` and even removed and re-installed conda. However, the same Kernel error comes back. 

Do you have an idea what is causing this?

**Comment by emolinaro** [comment]
@vincentvanhees are you running `jupyter notebook` from the activated conda environment? It looks like it is trying to use another kernel.

**Comment by vincentvanhees** [comment]
Yes I am. I run `jupyter notebook` from within the conda environment.
Do you think scheduling a short call would help to resolve this?

**Comment by vincentvanhees** [comment]
@emolinaro update - I just managed to fix the problem by deleting  ~/.local/share/jupyter/kernels/python3/kernel.json.
